### ISSUE TITLE
Unify libraries to GTK

### ISSUE THREAD

**Issue by JoaquinDecima** [codesardine/Jadesktop#105]
I think the ideal would be to unify the libraries to be able to generate a better integration between the Environment and the apps that surround it. I think the best thing would be to do it with GTK since with V3 we can reuse the CSS to unify the appearance of the desktop with the apps and Mutter or Gala

**Comment by codesardine** [comment]
Gtk CSS does not define appearance on the desktop it defines appearance of your applications, Gala can be replaced for whatever you want.
For uniform look check here. https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications
