### ISSUE TITLE
Rebase to neutralino JS

### ISSUE THREAD

**Issue by JoaquinDecima** [codesardine/Jadesktop#106]
Neutralino JS is a project that could improve the performance of this project. JAK is well made but it consumes much more than NeutralinoJS does.

Is it possible to make a rebase? Do you see it useful?

I don't want you to take it as a bad thing, I just think it could improve the project.

https://github.com/neutralinojs/neutralinojs

**Comment by codesardine** [comment]
Nodejs does not have the required API and if it had i would require to do it again from scratch.

**Comment by JoaquinDecima** [comment]
**NeutralinoJS** has an **API** closer to the system. These functionalities could even be added. I saw that JAK and the QT browser implementation are **too heavy**.

Currently try to integrate an application bar in the HTML so as not to use an external one. But the consumption of JAK is alarming. 

I will try to migrate the project to Neutralino (Or rather a fork) To reduce consumption by passing the backend to C. Also separate the HTML and CSS to a vue project. The same when compiled in production mode allows to optimize calls and load in memory, it is not a difficult job.
