### ISSUE TITLE
How to build new theme

### ISSUE THREAD

**Issue by JoaquinDecima** [codesardine/Jadesktop#108]
Hi, I'm testing with JADE. I would like to know if the VUE project is not compiled. I am trying to make abrupt changes to the interface but it generates binding errors.

**Comment by codesardine** [comment]
Vue is not compiled.

**Comment by JoaquinDecima** [comment]
Yes, sorry I thought it was like React, or Angular. Even so, I think there is a lack of documentation when making some changes many errors are generated

**Comment by codesardine** [comment]
Vue can be compiled, however I did not go with that, vue holds some of the functionality including search as it was easier to use Vue that build a search from scratch.

https://vuejs.org/v2/guide/
