### ISSUE TITLE
App Some Features.

### ISSUE THREAD

**Issue by Secara** [codesardine/Jadesktop#37]
It would be great if one could open all this via the webbrowser on another device which is in the same network. And even better if there was a smartphone, tablet and TV optimization.
If you would help with the necessary work, I could intimate your GUI into my current project.

**Comment by codesardine** [comment]
Hi @Secara, using with your TV is easy just plug it in your hdmi and use a wireless mouse and or keyboard, you can also install a onscreen keyboard from Manjaro repository's.

issue #30 will fix touchscreen.
Using smartphone, tablet wont depend totally in Jade if the applications you launch with the dash wont support tablet or smartphone then there is no point in doing this, Also Manjaro Linux wont work on ARM platform. 

Over the network can be possible using the Gtk Broadway backend, unfortunately is not working, and i have some other issues to address first, also you will need to setup some sort off 2 way Authentication, or anyone could eventually access your desktop remotely.  see issue codesardine/Jade-Application-Kit#2 

Integrating on your current project, could probably be done depending on what is your project about.

In the future please use descriptive titles in your issues, and do separate issues for different features you would like to see as that makes it easy to deal with. 

for example: Add Ability for Jade to talk with other applications using Dbus.
