### ISSUE TITLE
No module named j.AK

### ISSUE THREAD

**Issue by pavroo** [codesardine/Jadesktop#48]
Hi
I have debianized jade-menu-data, jade-applications-kit and jade-desktop, and installed them on Debian testing Buster 64bit.
All builds fine, but can't open a html file and run the jade dashboard.
The output:
`jade-desktop
Ops something went wrong: No module named j.AK
/opt/jade/jade-dashboard:26: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, WebKit2, Gio, Notify
/opt/jade/jade-dashboard:26: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, WebKit2, Gio, Notify
Traceback (most recent call last):
  File "/opt/jade/jade-dashboard", line 27, in <module>
    from functools import lru_cache as cache
ImportError: cannot import name lru_cache
`
The j module is installed in: /usr/lib/python3.6/dist-packages/  dir.
What I miss?
Regards
pavroo

**Comment by codesardine** [comment]
/usr/lib/python3.6/site-packages/  should be the correct directory.

running ( python setup.py install ) in your package will install in the correct folder.

**Comment by pavroo** [comment]
I did as you said, with no luck, so...
Removed debs and did try to install via the python command, output is (install na dbuild the same):
`python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open(path.join(readme, 'README.rst'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function`
Any suggestion, please?

**Comment by codesardine** [comment]
Are you using python 3. series, ? 
have a look here he was able to run it in Ubunto
https://github.com/codesardine/Jadesktop/issues/39

**Comment by pavroo** [comment]
That's the point. The python scripts use python 2 as default, so changed python to python3 in the headers of jak & jade-dashboard.
And no need to install "j" module in the 'site-packages' dir; built deb via dh-python installed it in the 'dist-packages' and works fine.
All together, the jade dash installed and works fine.
All debs can be installed from SparkyLinux repos.
Thank's.

**Comment by codesardine** [comment]
Glad to hear, completely forgot about the headers, will fix that soon, thanks

**Comment by codesardine** [comment]
Hi @pavroo 

your Jade post needs to be more specific as people going there think it is a sparkylinux project when is not.

https://www.phoronix.com/scan.php?page=news_item&px=Linux-Jade-Desktop-Environment

**Comment by pavroo** [comment]
Good Lord, didn't expect that, sorry.
Fixed now.

**Comment by codesardine** [comment]
@pavroo thank you

**Comment by codesardine** [comment]
another thing remove python-xdg as a dependency and add python-xdg3 or it wont work  :+1:
