### ISSUE TITLE
replace notes with a music player

### ISSUE THREAD

**Issue by codesardine** [codesardine/Jadesktop#53]
randomly play songs from Music folder

**Comment by MontiniCristian** [comment]
Yeah, it would be great!

**Comment by MontiniCristian** [comment]
A very nice solution would be integrate this issue with issue #13 giving to users the control of music flow thanks to Jasper.
Jasper also already supports Spotify APIs.

**Comment by codesardine** [comment]
I was thinking something a bit more generic, like local music, online music and jasper perhaps in the future.

**Comment by MontiniCristian** [comment]
Anyway, good idea
