### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JoaquinDecima** [codesardine/Jadesktop#62]
Sorry for the disturbances

I can not find the documentation of how to compile and install JADE, check the wiki without success!

Thank you!

**Comment by codesardine** [comment]
Jade does not need to be compiled, you install all the dependency's mentioned in the readme file, download from github and run from any folder.

Dependency's might have a different name  depending on the distribution or you can download a pre made distro: https://sourceforge.net/projects/manjaro-webdad/

**Comment by JoaquinDecima** [comment]
Me gustaría crear una distro que utilice JADE como escritorio base, y para eso me gustarai poder actualizarlo. ¿Existe posibilidad de compilarlo en .deb por ejemplo para poder ofrecer actualizaciones?

**Comment by codesardine** [comment]
If you want to build a debian package, start by reading the debian wiki or you can have a look at sparky linux  is debian based and they have packaged JADE.

Anyway this is not related at all with JADE, distro makers have to do there own packages as I only support Manjaro.

**Comment by codesardine** [comment]
Maybe this will help.
https://sparkylinux.org/repo/pool/main/j/jadesktop/
https://sparkylinux.org/repo/pool/main/j/jade-menu-data/
https://sparkylinux.org/repo/pool/main/j/jade-application-kit/
