### ISSUE TITLE
Install on Arch-Linux

### ISSUE THREAD

**Issue by LinArcX** [codesardine/Jadesktop#63]
Hi. the project has a wonderful idea and it is very nice.
I want to install it in arch linux just like any other DE(like: gnome, cinnamon, etc...)
How to do that?

**Comment by codesardine** [comment]
You can find all the related packages here.
https://gitlab.manjaro.org/packages/community/webdad

**Comment by LinArcX** [comment]
Install all of them?
I have sddm. after install it is added to the menu to select and login?

**Comment by codesardine** [comment]
You will be building your own distro based on arch and will have to dig in configuration files, I already done that so others don't have to, give this a spin.
https://sourceforge.net/projects/manjaro-webdad/files/

**Comment by LinArcX** [comment]
I know, but if anybody want to keep current arch distro and add another DE, what should he/she do?

**Comment by codesardine** [comment]
Install jade-dashboard and dependecys. It will run as an application with any DE.
