### ISSUE TITLE
Use GTK instead of HTML

### ISSUE THREAD

**Issue by yusdacra** [codesardine/Jadesktop#78]
This desktop is pretty nice, but have you considered using GTK instead of HTML? I think that HTML as a programming language is pretty good, but GTK is the new hot stuff. It's like, HTML 2.0! It also uses more RAM, so no RAM goes unused! If you could use that, it would be appreciated :)

**Comment by cheddar-cheeze** [comment]
![#soydev](https://c10.patreonusercontent.com/3/eyJ3Ijo0MDB9/patreon-media/p/reward/3514257/9c0407b96d4b4ddd81bf4ff3b10a6ab6/1.png?token-time=2145916800&token-hash=jetXdybBr_nP9q4QJuuMZrb2bRNkaQbx4jwIQpxsHW0%3D)

**Comment by codesardine** [comment]
There is already many GTK desktops, 250mb ram is not an issue on modern hardware.
