### ISSUE TITLE
Super key open applications menu.

### ISSUE THREAD

**Issue by Shickmo** [codesardine/Jadesktop#83]
I saw another issue mentioning keyboard support. That said was curious what the super key will be tied to action wise. It seems like it would be a good fit to open the applications menu and if you begin typing it woupd perform the search. Perhaps food for thought as you are addong keyboard support.

Thanks :)

**Comment by codesardine** [comment]
That could be done.

**Comment by codesardine** [comment]
Key shortcuts are better done using your window manager.
