### ISSUE TITLE
[Request] How to compile it for Ubuntu?

### ISSUE THREAD

**Issue by DaniellMesquita** [codesardine/Jadesktop#86]

**Comment by codesardine** [comment]
No need to compile install all needed packages from ubunto repos.
install pip and jade-application-kit from pip repos.  

also have a look here.
https://github.com/codesardine/Jadesktop/issues/39

**Comment by codesardine** [comment]
If you need any help running on ubunto let me know.

**Comment by DaniellMesquita** [comment]
Can it work as replacement to XFCE's desktop?
XFCE is a modular environment, which could work replacing its desktop.

**Comment by codesardine** [comment]
There is a standalone concept here you can try:
https://sourceforge.net/projects/manjaro-webdad/
