### ISSUE TITLE
Can you please move up the Jade Logo

### ISSUE THREAD

**Issue by adamofbremen** [codesardine/Jadesktop#89]
I am using Jade Desktop on Linux Mint Cinnamon Edition, with multiple desktops running at the same time, works very very well.  Screenshot is attached.  As you will see, the Jade logo is cropped by the menu panel in Cinnamon, on the auto-hide setting, which is nice with Jade Desktop.

I am the developer of Jade 5GL, a programming language for GUI generation of trivial python programs.  I am incorporating Jade Desktop into a Gnu/Jade Operating System containing my Jade 5GL language.  I am sure, once it is ready for release, you would be interested in it.

I installed from Sparky Linux repository and it failed to find j.AK.  I copied the j folder to opt/jade seemed to fix it pretty quick.  Otherwise the install from Sparky Linux worked well as a Desktop Application.

Jade Desktop integrates flawlessly with Cinnamon to create a super-desktop which I am going to explore as the launching pad for my 5GL programs.

Best wishes with your Jade Desktop environment  It is very nice and just in time for 2020.

![image](https://user-images.githubusercontent.com/59138258/71321606-bdc87b80-24b3-11ea-8158-d96f684cd13b.png)

**Comment by adamofbremen** [comment]
... also, it is using the file in /opt/jade/ rather than the local folder icon for the J logo on the Desktop.

If I copy the j folder from opt/jade to the place I downloaded the rest of the application, besides this icon issue, everything seems to work for Jadesktop inside another Window Manager.

It would make it easier for newbies if, after they download the code into a folder, it just works, without installation.  That it will do with these two small changes.

**Comment by adamofbremen** [comment]
oops - only if they have the main dependencies installed, which I have, probably due to me installing jadesktop from sparkylinux repository - sorry

**Comment by adamofbremen** [comment]
One more thing ... I see the screenshot shows the bug of the windows timing out back to the notes screen.  Here is the screenshot of how it looks before the timeout happens.  You might see then the advantages of it not doing it :)

![screen](https://user-images.githubusercontent.com/59138258/71323991-7224ca80-24d1-11ea-976f-36c87685fac6.jpg)

**Comment by codesardine** [comment]
You may want to try https://manjaro.org/download/ Cinnamon, I package my releases there.

Do you have a link for (Jade 5GL)?

Closing this as those issues are irrelevant for the upcoming version.

**Comment by adamofbremen** [comment]
On Sat, 2020-01-04 at 08:59 -0800, Vitor Lopes wrote:
> You may want to try https://manjaro.org/download/ Cinnamon, I package
> my releases there.

Thanks for that, i'll give it a spin on a usb stick
> Do you have a link for (Jade 5GL)?

Not at the moment, I am still developing it and I am the only person
using it right now,  so that I can evolve it quickly.
As soon as it is stable I will post it to Github and let you know.
Best wishesAdam
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/codesardine/Jadesktop/issues/89?email_source=notifications\u0026email_token=AODGBUSSRNADOAOWKFUNBV3Q4C6AXA5CNFSM4J6LQCEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIC3ZEI#issuecomment-570801297
> ",
> "url": "
> https://github.com/codesardine/Jadesktop/issues/89?email_source=notifications\u0026email_token=AODGBUSSRNADOAOWKFUNBV3Q4C6AXA5CNFSM4J6LQCEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIC3ZEI#issuecomment-570801297
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
