### ISSUE TITLE
Closing Jade Desktop back to the main desktop

### ISSUE THREAD

**Issue by adamofbremen** [codesardine/Jadesktop#90]
There is no option to close the program Jade Desktop when it is running as a secondary desktop under another window manager.  It causes a delay in the shutdown procedure (the wait 1.5 minutes) if it is not shut down tidily.

An additional option on the menu would be good to simply end the program.

**Comment by codesardine** [comment]
Closing this one as is not meant to work like that anymore, it can be killed from the shell.
