### ISSUE TITLE
Desktop Background Timing Out

### ISSUE THREAD

**Issue by adamofbremen** [codesardine/Jadesktop#92]
When there are multiple desktops running (say a Window Manager plus two Jade Desktops, each set to a different application list) when switching back to a previous Jade Desktop, as soon as you enter the application it times out back to the main JADE WALLPAPER, (ie: shows the notes window on it) instead of the way it was when you left it.

It would be better to keep the arrangement so that one can have different sets of applications available from different Jade Desktops running at the same time, easily switching between them using the main panel of the 3rd party Window Manager.  In my case, Cinnamon.

**Comment by codesardine** [comment]
https://github.com/codesardine/Jadesktop/commit/81f5d328fd5306e8c295116bd82c5dca0ee247af
